workflows:
  android-release:
    name: Android Release

    environment:
      node: 20
      java: 17

    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab